name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build static site for GitHub Pages
        run: npm run build:static
        env:
          BUILD_PLATFORM: github-pages
          GITHUB_PAGES: true
          # API Keys from GitHub Secrets (optional - app works in demo mode without them)
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Display deployment info
        run: |
          echo "🚀 Successfully deployed to GitHub Pages!"
          echo "🔗 Site URL: ${{ steps.deployment.outputs.page_url }}"
          echo "🔐 API Keys: $([ -n "${{ secrets.OPENAI_API_KEY }}" ] && echo "OpenAI ✅" || echo "OpenAI ❌") $([ -n "${{ secrets.GEMINI_API_KEY }}" ] && echo "Gemini ✅" || echo "Gemini ❌") $([ -n "${{ secrets.ANTHROPIC_API_KEY }}" ] && echo "Anthropic ✅" || echo "Anthropic ❌")" 